package utils;

public interface Const {
    String SEARCH_USER = "SEARCH_USER";
    String SEARCH_CAR = "SEARCH_CAR";
    String SEARCH_FINE = "SEARCH_FINE";
    String PASSPORT = "PASSPORT";
    String SEARCH_USER_PASSPORT = "SEARCH_USER_PASSPORT";
    String SEARCH_USER_ID = "SEARCH_USER_ID";
    String SEARCH_FINE_BY_CAR_NUMBER = "SEARCH_FINE_BY_CAR_NUMBER";
    String SEARCH_FINE_BY_CAR_NUMBER_AND_MONTH = "SEARCH_FINE_BY_CAR_NUMBER_AND_MONTH";
    String BACK = "◀️BACK";
}
